## COMPETIDORES
### CREATE
POST localhost:8080/v1/competidor
Content-Type: application/json

{
  "nome": "André Moraes",
  "idade": 27,
  "cidadeNatal": {
    "cidade": "Agudos",
    "estado": "SP"
  }
}

### LIST
GET localhost:8080/v1/competidor

### PROCURA
GET localhost:8080/v1/competidor/203

### ATUALIZA
PUT localhost:8080/v1/competidor/152
Content-Type: application/json

{
  "nome": "Robson Palermo",
  "idade": 22,
  "cidadeNatal": {
    "cidade": "Rio Branco",
    "estado": "AC"
  }
}


### DELETE
DELETE localhost:8080/v1/competidor/203

## TROPEIROS

### LIST
GET localhost:8080/v1/tropeiro

### CREATE
POST localhost:8080/v1/tropeiro
Content-Type: application/json

{
  "nome": "Paulo Emilio",
  "sigla": "PE",
  "boiada": [
    {
      "nome": "Europeu",
      "ladoBrete": "CERTO"
    }
  ]
}

### BUSCA
GET localhost:8080/v1/tropeiro/152

### ATUALIZA
PUT localhost:8080/v1/tropeiro/2
Content-Type: application/json

{
  "nome": "Neto Oger BRAHMA",
  "sigla": "NO"
}

### DELETE
DELETE localhost:8080/v1/tropeiro/203

## Animais

### LISTA
GET localhost:8080/v1/animal

### BUSCA
GET localhost:8080/v1/animal/2

### CRIA
POST localhost:8080/v1/animal
Content-Type: application/json

{
  "nome": "Estradeiro",
  "ladoBrete": "CERTO",
  "proprietario": {
    "id": 403
  }
}

### Atualiza
PUT localhost:8080/v1/animal/154
Content-Type: application/json

{
  "nome": "Bandoleiro",
  "ladoBrete": "CERTO"
}

### DELETE
DELETE localhost:8080/v1/animal/204

## EVENTOS

### LISTAR
GET localhost:8080/v1/evento

### BUSCAR
GET localhost:8080/v1/evento/1

### CRIAR
POST localhost:8080/v1/evento
Content-Type: application/json

{
  "titulo": "Barretos International Rodeo 2004",
  "localizacao": {
    "cidade": "Barretos",
    "estado": "SP"
  }
}

### Atualiza
PUT localhost:8080/v1/evento/52
Content-Type: application/json

{
  "titulo": "FEPEINA 2024 - 50 anos",
  "localizacao": {
    "cidade": "Douradina",
    "estado": "PR"
  }
}

### Deleta
DELETE localhost:8080/v1/evento/52

## Inscrição Competidor Evento
### CRIA
POST localhost:8080/v1/competidor/361/evento
Content-Type: application/json

{
  "id": 102
}